# Generated by Django 6.0 on 2025-12-27 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('caracteristicas', models.TextField(blank=True, verbose_name='Características')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='empresas.empresa')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('COP', 'Peso colombiano'), ('USD', 'Dólar'), ('EUR', 'Euro')], max_length=3, verbose_name='Moneda')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='productos.producto')),
            ],
            options={
                'db_table': 'producto_precio',
                'constraints': [models.UniqueConstraint(fields=('producto', 'moneda'), name='uq_producto_precio__producto_moneda')],
            },
        ),
    ]
