# Generated by Django 6.0 on 2025-12-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_initial_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
